import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "react-hot-toast";
// import { ThemeProvider } from "next-themes";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {/* <ThemeProvider > */}
          <Toaster position="bottom-right" />
          {children}
        {/* </ThemeProvider> */}
      </body>
    </html>
  );
}
